drop table service_provider_group_acl ;
drop table group_provider ;
drop table group_provider_user_oauth;
drop table group_provider_decorator;
drop table group_provider_decorator_option;
drop table group_provider_filter ;
drop table group_provider_filter_option ;
drop table group_provider_option ; 
drop table group_provider_precondition ;
drop table group_provider_precondition_option ;
