create table service_provider_group_acl (
        id bigint generated by default as identity (start with 1),
        group_provider_id bigint not null,
        spentityid varchar(1024) not null,
        allow_groups bit,
        allow_members bit,
        primary key (id)
);
create table group_provider (
  id bigint generated by default as identity (start with 1),
  identifier varchar(255) not null,
  name varchar(255) not null,
  classname varchar(255) not null,
  primary key (id)
);
create table group_provider_user_oauth (
  provider_id varchar(255) not null,
  user_id varchar(255) not null,
  oauth_token varchar(1024) not null,
  oauth_secret varchar(1024) not null,
  primary key (provider_id,user_id)
);
create table group_provider_decorator (
  id bigint generated by default as identity (start with 1),
  group_provider_id bigint not null,
  classname varchar(255) not null ,
  primary key (id)
) ;
create table group_provider_decorator_option (
  group_provider_decorator_id bigint not null,
  name varchar(255) not null ,
  value varchar(255) not null ,
  primary key (group_provider_decorator_id,name)
);
create table group_provider_filter (
  id bigint generated by default as identity (start with 1),
  group_provider_id bigint not null,
  type varchar(255) not null ,
  classname varchar(255) not null ,
  primary key (id)
);
create table group_provider_filter_option (
  group_provider_filter_id bigint not null,
  name varchar(255) not null ,
  value varchar(255) not null ,
  primary key (group_provider_filter_id,name)
);
create table group_provider_option (
  group_provider_id bigint not null,
  name varchar(255) not null ,
  value varchar(255) not null ,
  primary key (group_provider_id,name)
); 
create table group_provider_precondition (
  id bigint generated by default as identity (start with 1),
  group_provider_id bigint not null,
  classname varchar(255) default null,
  primary key (id)
);
create table group_provider_precondition_option (
  group_provider_precondition_id bigint not null,
  name varchar(255) not null ,
  value varchar(255) not null ,
  primary key (group_provider_precondition_id)
);

insert into service_provider_group_acl (id, group_provider_id, spentityid, allow_groups, allow_members) values (1, 9, 'https://serviceregistry.test.surfconext.nl/simplesaml/module.php/saml/sp/metadata.php/default-sp', 1, 1);
insert into service_provider_group_acl (id, group_provider_id, spentityid, allow_groups, allow_members) values (2, 9, 'https://teams.test.surfconext.nl/shibboleth', 1, 1);

insert into group_provider_user_oauth (provider_id, user_id, oauth_token, oauth_secret) values ('avans','urn:collab:person:test.surfguest.nl:tester', 'ba786086238d01f81ae481f3c11bee67ebd88b6a', 'e52887d1140e633f3c58bbe1677fc6766c30650d');
insert into group_provider_user_oauth (provider_id, user_id, oauth_token, oauth_secret) values ('hz', 'urn:collab:person:test.surfguest.nl:tester2', '20ce1240-735f-4752-8269-1449b10a32ee', 'c7106d17-6cd0-4a73-856d-994462b85982');

insert into group_provider (id, identifier, name, classname) values (4, 'hz', 'HZ', 'EngineBlock_Group_Provider_OpenSocial_Oauth_ThreeLegged');
insert into group_provider (id, identifier, name, classname) values (5, 'grouper', 'SURFteams grouper', 'EngineBlock_Group_Provider_Grouper');
insert into group_provider (id, identifier, name, classname) values (9, 'avans', 'Avans', 'EngineBlock_Group_Provider_OpenSocial_Oauth_ThreeLegged');