--
-- Table structure for table `text_content`
--

CREATE TABLE IF NOT EXISTS `text_content` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `field` varchar(255) DEFAULT NULL,
  `text` longtext,
  PRIMARY KEY (`id`),
  UNIQUE KEY `field` (`field`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `text_content` (`id`,`field`,`text`)
VALUES
	(1,'intro-component-introduction','<div class=\"intro-comp-title-bar\"><h2 class=\"intro-comp-title\">Make Online Collaboration Easy</h2></div>\n<div class=\"intro-comp-content\">\n<p>\nAre you tired of storing all your passwords and visiting multiple sites to satisfy your online collaboration needs? Do you wish to select your favorite online collaboration tools and to use them together? This portal lets you select a still growing library of collaboration tools, arrange them according to your personal needs and group context, access them with one single account, without having to visit multiple sites!\n<br /><strong class=\"attention\">Try it NOW!</strong>\n</p>\n</div>'),
	(2,'intro-component-getting-started','<div class=\"intro-comp-title-bar\"><h2 class=\"intro-comp-title\">Getting started in just 5 steps</h2></div>\n  <div class=\"intro-comp-content help\">\n    <ol>\n      <li><span class=\"nr\">1</span><a href=\"https://wiki.surfnetlabs.nl/display/conextsupport/Logon\" class=\"external-link h3\" target=\"_blank\" rel=\"nofollow\">Logon with your own institutional account</a>\n        <ul>                    \n          <li>choose your institution in de dropdown above</li>\n          <li>provide your credentials</li>\n        </ul>\n      </li>\n      <li><span class=\"nr\">2</span><a href=\"https://wiki.surfnetlabs.nl/display/conextsupport/Tabs\" class=\"external-link h3\" target=\"_blank\" rel=\"nofollow\">Create your collaboration tabs</a>\n        <ul>\n          <li>choose \"Tab+\" and add as many as you like for personal use or to use with your co-workers</li>\n          <li>arrange them as you like</li>\n        </ul>\n      </li>\n      <li><span class=\"nr\">3</span><a href=\"https://wiki.surfnetlabs.nl/display/conextsupport/Gadgets\" class=\"external-link h3\" target=\"_blank\" rel=\"nofollow\">Choose your favorite collaboration gadgets</a>\n        <ul>\n          <li>see what is available for you</li>\n          <li>add and start collaborate</li>\n        </ul>\n      </li>\n      <li><span class=\"nr\">4</span><a href=\"https://wiki.surfnetlabs.nl/display/conextsupport/Teams\" class=\"external-link h3\" target=\"_blank\" rel=\"nofollow\">Create a team</a>\n        <ul>\n          <li>add your co-workers</li>\n          <li>set their privileges</li>\n          <li>use your team in a tab and multiple collaboration tools</li>\n        </ul>\n      </li>\n      <li><span class=\"nr\">5</span><a href=\"https://wiki.surfnetlabs.nl/display/conextsupport/Share\" class=\"external-link h3\" target=\"_blank\" rel=\"nofollow\">Share a tab with your team members</a>\n        <ul>\n          <li>select a tab you would like to share</li>\n          <li>send a snapshot of that tab, its gadgets and settings</li>\n          <li>and start collaborate &#33;</li>                      \n        </ul>\n      </li>\n    </ol>\n    <p>For more information and help, please visit our <a href=\"https://wiki.surfnetlabs.nl/display/conextsupport/Getting+started\" target=\"_blank\">knowledgebase</a></p>\n  </div>\n</div>');